const ShopActionTypes = {
  FETCH_COLLECTIONC_START: "FETCH_COLLECTIONC_START",
  FETCH_COLLECTIONC_SUCCESS: "FETCH_COLLECTIONC_SUCCESS",
  FETCH_COLLECTIONC_FAILURE: "FETCH_COLLECTIONC_FAILURE",
};

export default ShopActionTypes;
